### 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written and reusable code modules that can be easily imported and used in Python scripts or programs. These libraries contain functions, classes, and methods that address specific tasks or provide specific functionalities, allowing developers to leverage existing code rather than writing everything from scratch.

  There are several reasons why Python libraries are widely used:

1. Code Reusability: Libraries provide a set of functions and tools that can be reused across different projects, saving time and effort for developers.

2. Efficiency: Using established libraries allows developers to benefit from optimized and well-tested code, leading to more efficient and reliable programs.

3. Specialized Functionality: Many libraries are designed to address specific tasks or domains, such as data analysis, machine learning, web development, or scientific computing. By using these specialized libraries, developers can focus on their application logic rather than low-level details.

4. Community Collaboration: Python has a large and active community that contributes to the development of various libraries. This collaborative effort results in a wide range of high-quality libraries that cater to different needs.

5. Interoperability: Python libraries are often designed to work seamlessly with each other, promoting interoperability and making it easy to combine different tools to achieve complex tasks.

6. Rapid Development: By leveraging existing libraries, developers can speed up the development process and meet project deadlines more effectively.

Popular Python libraries include NumPy for numerical computing, Pandas for data manipulation and analysis, Matplotlib for data visualization, TensorFlow and PyTorch for machine learning, Flask and Django for web development, and many more.

In summary, Python libraries enhance productivity, enable code reuse, and provide access to a vast ecosystem of tools and functionalities, making Python a versatile and powerful programming language.

### 2. What is the difference between Numpy array and List?


NumPy arrays and Python lists are both used to store and manipulate collections of data, but there are several key differences between them:

Data Type and Homogeneity:

   Numpy Array: Numpy arrays are homogeneous, meaning all elements of the array must be of the same data type. This allows for more efficient storage and faster operations on the data.
   
   List: Lists can contain elements of different data types, and each element can be a different type. This flexibility comes at the cost of increased memory overhead and potentially slower performance.


Performance:

   Numpy Array: Numpy arrays are more efficient for numerical operations and large datasets. They are implemented in C and have a contiguous block of memory, enabling optimized mathematical operations.
   
   List: Lists are more general-purpose and may not perform as well as NumPy arrays, especially for large datasets or numerical computations.


Size and Memory Overhead:

   Numpy Array: Numpy arrays have a more compact representation in memory compared to lists, which can lead to lower memory overhead for large datasets.
   
   List: Lists have more overhead due to their flexibility, which can result in larger memory consumption.


Syntax and Functionality:

   Numpy Array: Numpy provides a variety of functions and methods specifically designed for numerical operations on arrays. This includes element-wise operations, linear algebra functions, and statistical operations.
   
   List: Lists are more general-purpose and provide a broader range of built-in functions for general list manipulation. However, they lack the specialized functions for numerical operations found in NumPy.


Dimensionality:

   Numpy Array: Numpy arrays can be multi-dimensional, allowing for the representation of matrices, tensors, and other complex data structures.
   
   List: Lists are one-dimensional and need to be nested to represent multi-dimensional structures, which can be less convenient for certain types of operations.

### 3. Find the shape, size and dimension of the following array?

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print(arr) # print array
print("shape:- ",np.shape(arr))  # this function is use for find shape of array
print("size:- ",np.size(arr))  # this function is use for  find size of array
print("dimension:- ",np.ndim(arr)) # this function is use for  find dimension of array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape:-  (3, 4)
size:-  12
dimension:-  2


### 4. Write python code to access the first row of the following array?

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print(arr) #print array
print("First row:-", arr[0]) # using array slicing and get 0th index of row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row:- [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print(arr) # print array
print("ans is:- ",arr[2,3]) # using array slicing and get 2ed index of raw and 3ed index of column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ans is:-  12


### 6. Write code to extract all odd-indexed elements from the given numpy array?

In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print("Original array:-\n",arr) # print array

result = arr[:,1::2] 
print("odd-indexed array:-")
print(result)

Original array:-
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
odd-indexed array:-
[[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
# create a random array between 0 and 1
arr = np.random.rand(3,3) # use rand function for generate  matrix with values between o and 1
arr 

array([[0.44570411, 0.7114922 , 0.46978832],
       [0.10282527, 0.39582979, 0.23591058],
       [0.89227888, 0.45216655, 0.13679343]])

### 8. Describe the difference between np.random.rand and np.random.randn?

In [7]:
# Generates random values from a uniform distribution between 0 (inclusive) and 1 (exclusive).
arr1 = np.random.rand(3,3)

# Generates random values from a standard normal distribution (mean = 0, standard deviation = 1).
arr2 = np.random.randn(3,3)

print(arr1)
print()
print(arr2)

[[0.02182329 0.29489275 0.11905751]
 [0.90402672 0.38126259 0.89893198]
 [0.79907564 0.45746458 0.88437565]]

[[-0.42614563 -0.29911167  1.2567879 ]
 [-0.6889979  -0.7063268  -0.21085075]
 [ 0.83659384  0.2537455   0.20282261]]


### 9. Write code to increase the dimension of the following array?

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print("Original array:-\n",arr) # print array

arr2 = arr[:, :,np.newaxis] # newaxis is use for increase dimension in array
print("increase dimension:- ")
print(arr2)

Original array:-
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
increase dimension:- 
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


### 10. How to transpose the following array in NumPy?

In [9]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # make a array using numpy
print("This is original array")
print(arr) # print array
print("This is transpose array.")
print(arr.T) # this function is use for transpose in array

This is original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
This is transpose array.
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:

In [10]:
# create two array and give name m_a and m_b
m_a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]) 
m_b = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
# print both matrix
print(m_a)
print()
print(m_b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# 1. Index wise multiplication
result = m_a * m_b 
print(result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [13]:
# 2. Matrix multiplication

result = m_a @ m_b.T
print(result)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [14]:
# 3. Add both the maticx

result = m_a + m_b
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [15]:
# 4. Subtract matrix B From A

result = m_a - m_b
print(result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
# 5. Divide Matrix B by A

result = m_b / m_a
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

In [17]:

'''
In NumPy, the byteswap() function can be used to swap the byte order of an array. This function is used 
to change the endianness (byte order) of the array elements. It returns a new array with the byte order 
swapped. Here's an example:
'''
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4], dtype=np.float32)

# Swap the byte order
swapped_array = original_array.byteswap()

# Display the original and swapped arrays
print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1. 2. 3. 4.]

Swapped Array:
[4.6006e-41 8.9683e-44 2.3049e-41 4.6007e-41]


### 13. What is the significance of the np.linalg.inv function?

In [18]:
# Coefficient matrix A
A = np.array([[2, 1],
              [4, -3]])
# Use np.linalg.inv to compute the inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.3  0.1]
 [ 0.4 -0.2]]


### 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It returns a new array with the specified shape, and the original array remains unchanged.

In [19]:
arr = np.array([1,2,3,4,5,6,7,8]) # create an array 
np.reshape(arr, (2,4)) # give two rows and 4 columns for reshape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 15. What is broadcasting in Numpy?


Broadcasting in NumPy is a powerful feature that allows arrays with different shapes to be combined and operated on together. It enables you to perform element-wise operations on arrays of different shapes without explicitly reshaping them, making it more convenient and efficient.

In [20]:
# create two array
arr1 = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4]]) # create an array
arr2 = np.array([1,2,3,4]) 

In [21]:
# print first array
print("arr1:-\n",arr1)
# print second array
print("\narr2:-\n",arr2)
# make a sum of matrix using brodcasting
print("\nFinal:-\n",arr1 + arr2)

arr1:-
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]

arr2:-
 [1 2 3 4]

Final:-
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [ 2  4  6  8]]
